### PR TITLE
NO-JIRA: Updated Python SDK fern autogenerated code

### PR DESCRIPTION
**Pull request by andrescrz**
## Details
I run the following script:

```bash
./scripts/generate_openapi.sh
```
So `sdks/python/code_generation/fern/openapi/openapi.yaml` was updated with the latest backend API, so all Python SDK Fern autogenerated code was updated under `sdks/python/src/opik/rest_api/` folder.

Triggering the backend build also caused Java code to be formatted with Spotless.

## Issues

N/A

## Testing
- Passed CI build.

## Documentation
N/A

### CODE REVIEW

**Review by thiagohora — APPROVED** [review]
We probably need to add format validation in the pipeline

**Comment by andrescrz** [comment]
> We probably need to add format validation in the pipeline

There's a Github action for this already:
- https://github.com/comet-ml/opik/actions/workflows/python_sdk_linter.yml

Also, the `./scripts/generate_openapi.sh` script automatically runs `pre-commit` and all Python SDK files.

**Comment by thiagohora** [comment]
> > We probably need to add format validation in the pipeline
> 
> There's a Github action for this already:
> 
> * https://github.com/comet-ml/opik/actions/workflows/python_sdk_linter.yml
> 
> Also, the `./scripts/generate_openapi.sh` script automatically runs `pre-commit` and all Python SDK files.

Yeah, I mean for Java, since many of your changes in Java were formatting. Anyway, it's approved.

**Comment by alexkuzmik** [comment]
Please update the readme in code_generation so that everybody know we now have this script

**Comment by andrescrz** [comment]
> > > We probably need to add format validation in the pipeline
> > 
> > 
> > There's a Github action for this already:
> > 
> > * https://github.com/comet-ml/opik/actions/workflows/python_sdk_linter.yml
> > 
> > Also, the `./scripts/generate_openapi.sh` script automatically runs `pre-commit` and all Python SDK files.
> 
> Yeah, I mean for Java, since many of your changes in Java were formatting. Anyway, it's approved.

That makes sense. We can do it in next PRs.

**Comment by andrescrz** [comment]
> Please update the readme in code_generation so that everybody know we now have this script

Done in revision 2.

**Review by thiagohora — APPROVED** [review]

**Pull request merged**
