### PR TITLE
[OPIK-50] Add cli.py

### PR DESCRIPTION
**Pull request by alexkuzmik**
## Details
Adds cli.py to support commands
`opik server install`
`opik server upgrade`

In case there are any extra arguments passed, opik cli ignores them and just passes to `opik-installer`.
If `opik-installer` is not installed, it's being installed when any of these commands is called.

## Testing
Tested manually, `opik server install` should trigger corresponding `opik-server install` command from `opik-installer` package. Similarly for `opik` server upgrade.

### CODE REVIEW

**Review by Nimrod007 — DISMISSED** [review]

**Comment by Nimrod007** [comment]
@AndreiCautisanu please test

**Comment by CRThaze** [comment]
At @alexkuzmik's request, I went ahead and made some changes to this PR to integrate the `opik-installer` package to the SDK (as a dependency) in such a way as to acheive the following goals:
- Keep a single parent `click.Context` (instead of subprocessing or invoking a second top-level instance of click)
- Prevent the heavy `ansible` dependencies from being installed by pip until invoking a command that requires it.

To accomplish this I:
- Added the dynamic installation of the heavy dependencies to `opik-installer` as a Click decorator.
- Ensured that we can still guarantee a minimum version of the `ansible-playbill` (and by proxy `ansible`) packages
- Adjusted the `debug_set` function to work properly when `opik-server` is not the root context, by traversing the each context generation.
- Changed how the Opik SDK's `cli.py` adds the `server` sub-group so that it simply uses the imported group from `opik-installer`
- Added some logic to `cli.py` to ensure that both `-v` and `-h` can be called on the root command (`opik -v` & `opik -h`) in the same way as in the `server` subcommand.

**Comment by alexkuzmik** [comment]
LGTM

**Comment by AndreiCautisanu** [comment]
**Tested on Mac**: issue with Docker Daemon start after starting Docker Desktop - cannot confirm whether this is fault of installer or not fully clean machine after uninstalling Docker Desktop to test. Summary: after uninstalling Docker and running installer, the Docker Desktop instance that is started with the `Open Docker Desktop` task throws an error or does not start at all, causing the `Wait for Docker daemon to start` task to fail due to a timeout. If Docker Desktop is already installed on the system or if it's restarted during installation - everything works fine. **Other than this, all ok**

**Tested on Linux**: all ok

**Review by japdubengsub — APPROVED** [review]

**Pull request merged**
